name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - name: Checkout
        run: |
          git config --global --add safe.directory "$(pwd)"
          git init
          git remote add origin "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          git fetch --depth=1 origin "${GITHUB_SHA}"
          git checkout "${GITHUB_SHA}"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test tests/ATProtoNet.Tests/ --no-build --configuration Release --verbosity normal

  package:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        run: |
          git config --global --add safe.directory "$(pwd)"
          git init
          git remote add origin "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          git fetch --depth=1 origin "${GITHUB_SHA}"
          git checkout "${GITHUB_SHA}"

      - name: Pack NuGet packages
        run: dotnet pack --configuration Release --output ./nupkgs

      - name: Push to Forgejo NuGet registry
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --source "https://git.grandiras.net/api/packages/Grandiras/nuget/v3/index.json" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --skip-duplicate
