name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build Release
        run: dotnet build --configuration Release -p:Version=${{ steps.version.outputs.VERSION }}

      - name: Run unit tests
        run: dotnet test tests/ATProtoNet.Tests/ --no-build --configuration Release

      - name: Pack NuGet packages
        run: |
          dotnet pack --configuration Release --output ./nupkgs \
            -p:Version=${{ steps.version.outputs.VERSION }}

      - name: Push to Forgejo NuGet registry
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --source "https://git.grandiras.net/api/packages/Grandiras/nuget/v3/index.json" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --skip-duplicate

      - name: Push symbol packages
        run: |
          dotnet nuget push ./nupkgs/*.snupkg \
            --source "https://git.grandiras.net/api/packages/Grandiras/nuget/v3/index.json" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --skip-duplicate
        continue-on-error: true
