name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - name: Checkout
        run: |
          git config --global --add safe.directory "$(pwd)"
          git init
          git remote add origin "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          git fetch --depth=1 origin "${GITHUB_REF}"
          git checkout FETCH_HEAD

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore --source https://api.nuget.org/v3/index.json

      - name: Build Release
        run: dotnet build --no-restore --configuration Release -p:Version=${{ steps.version.outputs.VERSION }}

      - name: Run unit tests
        run: dotnet test tests/ATProtoNet.Tests/ --no-build --configuration Release

      - name: Pack NuGet packages
        run: |
          dotnet pack --no-restore --configuration Release --output ./nupkgs \
            -p:Version=${{ steps.version.outputs.VERSION }}

      - name: Push to Forgejo NuGet registry
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --source "https://git.grandiras.net/api/packages/Grandiras/nuget" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --skip-duplicate

      - name: Push symbol packages
        run: |
          dotnet nuget push ./nupkgs/*.snupkg \
            --source "https://git.grandiras.net/api/packages/Grandiras/nuget" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --skip-duplicate
        continue-on-error: true

      - name: Extract changelog for release
        id: changelog
        run: |
          # Extract the section for this version from CHANGELOG.md
          VERSION="${{ steps.version.outputs.VERSION }}"
          # Use awk to extract content between the current version header and the next one
          BODY=$(awk "/^## \[${VERSION}\]/{found=1; next} /^## \[/{if(found) exit} found{print}" CHANGELOG.md)
          # Write to a temp file to preserve newlines
          echo "$BODY" > /tmp/release-notes.md

      - name: Create Forgejo release
        run: |
          # Install curl and jq if not available
          apt-get update -qq && apt-get install -y -qq curl jq > /dev/null 2>&1 || true
          curl -s -X POST \
            "https://git.grandiras.net/api/v1/repos/Grandiras/ATProto.NET/releases" \
            -H "Authorization: token ${{ secrets.NUGET_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg tag "${{ github.ref_name }}" \
              --arg name "v${{ steps.version.outputs.VERSION }}" \
              --arg body "$(cat /tmp/release-notes.md)" \
              '{tag_name: $tag, name: $name, body: $body, draft: false, prerelease: false}'
            )"
