using System.Text;
using ATProtoNet.LexiconGenerator.Schema;

namespace ATProtoNet.LexiconGenerator.CodeGen;

/// <summary>
/// Generates C# source code from parsed Lexicon schema documents.
/// Produces classes, records, enums, and client methods that match
/// the hand-written patterns already used in ATProtoNet.Lexicon.
/// </summary>
public sealed class CSharpEmitter
{
    private readonly string _namespacePrefix;

    public CSharpEmitter(string namespacePrefix = "ATProtoNet.Lexicon")
    {
        _namespacePrefix = namespacePrefix;
    }

    /// <summary>
    /// Emits C# source files from a Lexicon document.
    /// Returns a list of (relative file path, C# source content) pairs.
    /// </summary>
    public List<(string Path, string Content)> Emit(LexiconDocument doc)
    {
        var results = new List<(string, string)>();
        var ns = TypeMapper.NsidToNamespace(doc.Id, _namespacePrefix);

        // Group all definitions from this document into a single file
        var sb = new StringBuilder();
        EmitFileHeader(sb, ns, doc);

        var hasContent = false;

        foreach (var (defName, def) in doc.Defs)
        {
            switch (def.Type)
            {
                case "record":
                    EmitRecordType(sb, doc.Id, defName, def);
                    hasContent = true;
                    break;

                case "object":
                    EmitObjectType(sb, doc.Id, defName, def);
                    hasContent = true;
                    break;

                case "string" when def.Enum is { Count: > 0 }:
                    EmitStringEnum(sb, doc.Id, defName, def);
                    hasContent = true;
                    break;

                case "token":
                    EmitToken(sb, doc.Id, defName, def);
                    hasContent = true;
                    break;

                case "query":
                case "procedure":
                    // Skip XRPC methods for now — these generate client methods separately
                    break;

                case "subscription":
                    // Event streams are complex; skip for initial implementation
                    break;

                default:
                    // Other types (string without enum, integer, boolean, etc.)
                    // are typically used as inline property constraints, not standalone types
                    break;
            }
        }

        if (hasContent)
        {
            // Close the namespace
            sb.AppendLine("}");

            var fileName = GetFileName(doc.Id);
            results.Add((fileName, sb.ToString()));
        }

        return results;
    }

    /// <summary>
    /// Emits C# source files for all documents grouped by namespace authority.
    /// </summary>
    public List<(string Path, string Content)> EmitAll(IEnumerable<LexiconDocument> documents)
    {
        var results = new List<(string Path, string Content)>();
        foreach (var doc in documents)
        {
            results.AddRange(Emit(doc));
        }
        return results;
    }

    private void EmitFileHeader(StringBuilder sb, string ns, LexiconDocument doc)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated from Lexicon schema: {doc.Id}");
        sb.AppendLine("// Do not edit manually — regenerate with: atproto-lexgen csharp");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
    }

    private void EmitRecordType(StringBuilder sb, string nsid, string defName, LexiconSchema def)
    {
        var className = TypeMapper.DefToClassName(nsid, defName, "record");
        var typeValue = defName == "main" ? nsid : $"{nsid}#{defName}";
        var objectSchema = def.Record;

        EmitXmlDoc(sb, def.Description, 0);
        sb.AppendLine($"public sealed class {className}");
        sb.AppendLine("{");

        // $type property
        sb.AppendLine($"    [JsonPropertyName(\"$type\")]");
        sb.AppendLine($"    public string Type => \"{typeValue}\";");
        sb.AppendLine();

        // Properties from the record's object schema
        if (objectSchema?.Properties is not null)
        {
            EmitProperties(sb, objectSchema.Properties, objectSchema.Required, nsid);
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void EmitObjectType(StringBuilder sb, string nsid, string defName, LexiconSchema def)
    {
        var className = TypeMapper.DefToClassName(nsid, defName, "object");

        EmitXmlDoc(sb, def.Description, 0);
        sb.AppendLine($"public sealed class {className}");
        sb.AppendLine("{");

        if (def.Properties is not null)
        {
            EmitProperties(sb, def.Properties, def.Required, nsid);
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void EmitProperties(
        StringBuilder sb,
        Dictionary<string, LexiconSchema> properties,
        List<string>? required,
        string contextNsid)
    {
        var isFirst = true;
        var requiredSet = required is not null ? new HashSet<string>(required) : new HashSet<string>();

        foreach (var (propName, propSchema) in properties)
        {
            if (!isFirst)
                sb.AppendLine();

            isFirst = false;

            var csharpType = TypeMapper.GetCSharpType(propSchema, contextNsid, _namespacePrefix);
            var propertyName = TypeMapper.ToPascalCase(propName);
            var isRequired = requiredSet.Contains(propName);

            // XML doc if description is available
            EmitXmlDoc(sb, propSchema.Description, 4);

            // Constraint comments
            EmitConstraintComments(sb, propSchema);

            // [JsonPropertyName] attribute
            sb.AppendLine($"    [JsonPropertyName(\"{propName}\")]");

            // Property declaration
            if (isRequired)
            {
                sb.AppendLine($"    public required {csharpType} {propertyName} {{ get; init; }}");
            }
            else
            {
                // Optional properties are nullable
                var nullableType = csharpType.EndsWith('?') || csharpType == "JsonElement"
                    ? csharpType
                    : $"{csharpType}?";
                sb.AppendLine($"    public {nullableType} {propertyName} {{ get; init; }}");
            }
        }
    }

    private void EmitStringEnum(StringBuilder sb, string nsid, string defName, LexiconSchema def)
    {
        var enumName = TypeMapper.DefToClassName(nsid, defName, "string");

        EmitXmlDoc(sb, def.Description, 0);
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// Serialized as a string. Use the string constants in this static class");
        sb.AppendLine("/// rather than a C# enum to preserve AT Protocol wire compatibility.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine($"public static class {enumName}");
        sb.AppendLine("{");

        foreach (var value in def.Enum!)
        {
            var constName = TypeMapper.ToPascalCase(value);
            sb.AppendLine($"    public const string {constName} = \"{value}\";");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void EmitToken(StringBuilder sb, string nsid, string defName, LexiconSchema def)
    {
        var typeName = TypeMapper.DefToClassName(nsid, defName, "token");
        var tokenValue = defName == "main" ? nsid : $"{nsid}#{defName}";

        EmitXmlDoc(sb, def.Description, 0);
        sb.AppendLine("/// <remarks>AT Protocol token type — use the <see cref=\"Value\"/> constant.</remarks>");
        sb.AppendLine($"public static class {typeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string Value = \"{tokenValue}\";");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitXmlDoc(StringBuilder sb, string? description, int indent)
    {
        if (string.IsNullOrWhiteSpace(description))
            return;

        var prefix = new string(' ', indent);

        // Escape XML special characters
        var escaped = description
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");

        sb.AppendLine($"{prefix}/// <summary>");
        sb.AppendLine($"{prefix}/// {escaped}");
        sb.AppendLine($"{prefix}/// </summary>");
    }

    private static void EmitConstraintComments(StringBuilder sb, LexiconSchema schema)
    {
        var constraints = new List<string>();

        if (schema.MinLength is not null) constraints.Add($"minLength: {schema.MinLength}");
        if (schema.MaxLength is not null) constraints.Add($"maxLength: {schema.MaxLength}");
        if (schema.MinGraphemes is not null) constraints.Add($"minGraphemes: {schema.MinGraphemes}");
        if (schema.MaxGraphemes is not null) constraints.Add($"maxGraphemes: {schema.MaxGraphemes}");
        if (schema.Minimum is not null) constraints.Add($"minimum: {schema.Minimum}");
        if (schema.Maximum is not null) constraints.Add($"maximum: {schema.Maximum}");
        if (schema.Format is not null) constraints.Add($"format: {schema.Format}");
        if (schema.Default is not null) constraints.Add($"default: {schema.Default}");

        if (constraints.Count > 0)
        {
            sb.AppendLine($"    // Constraints: {string.Join(", ", constraints)}");
        }

        if (schema.KnownValues is { Count: > 0 })
        {
            sb.AppendLine($"    // Known values: {string.Join(", ", schema.KnownValues)}");
        }

        if (schema.Type == "union" && schema.Refs is { Count: > 0 })
        {
            sb.AppendLine($"    // Union of: {string.Join(", ", schema.Refs)}");
        }
    }

    private string GetFileName(string nsid)
    {
        var lastDot = nsid.LastIndexOf('.');
        var authority = lastDot >= 0 ? nsid[..lastDot] : nsid;
        var name = lastDot >= 0 ? nsid[(lastDot + 1)..] : nsid;

        var segments = authority.Split('.');
        var path = string.Join("/", segments.Select(TypeMapper.ToPascalCase));
        var fileName = TypeMapper.ToPascalCase(name);

        return $"{path}/{fileName}.g.cs";
    }
}
